hash-format = "sha256"

[[files]]
file = "mods/collective.pw.toml"
hash = "8fe9131affc3479f265383362d45dc8616f7733c2543e602faa4cdaddfd90d2f"
metafile = true

[[files]]
file = "mods/custom-credits.pw.toml"
hash = "29058436be8f3ae12ad8ab3bf9f35d3eca994bce20357234fe94d7db99fc2f00"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "9afe3bdc73747e9ee220a5a9ae352342134543585be7ebfdae2781232a348359"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "9dd464164f06671cd241541f28892f0a13a4c6cf5643d4d4165e3c5fb3845b35"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "72b15c13cfd2c26d1e70a18372471c51cd05602feac93a80f312db244e28308e"
metafile = true

[[files]]
file = "mods/lightmans-currency.pw.toml"
hash = "d2b661766f8a39e1bc56a1a83ea69032972a9742f3a987aa2374b306f6ee8a32"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "7e4132ddb8db632baac0b84a4b7ec3e88263ff51dadf813260e4be4f9d5b8bab"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "c6dd2d83bba2c10927d484edd7290cca4deddd4e74a881209278f02d47fd8208"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cf86920e345cfd6fec606e40a2554a0fb67ddd04ed019df3ad6fff075c99955e"
metafile = true

[[files]]
file = "mods/vics-point-blank.pw.toml"
hash = "8da4ea127802f2b48b2741bb16e1c2212f850aef523b41f0b8b7036aa7858df7"
metafile = true
