hash-format = "sha256"

[[files]]
file = "README.md"
hash = "40b410bbdd5f08f8e4ef2566409a96b7fab92589504463e334456e2e1b035aef"

[[files]]
file = "mods/claim-chunk.pw.toml"
hash = "57538a39a0cc70a6633fa697bd5ea67e9a925e7928883d87084cc5dbf68f1922"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "9dd464164f06671cd241541f28892f0a13a4c6cf5643d4d4165e3c5fb3845b35"
metafile = true

[[files]]
file = "mods/lightmans-currency.pw.toml"
hash = "d2b661766f8a39e1bc56a1a83ea69032972a9742f3a987aa2374b306f6ee8a32"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "7e4132ddb8db632baac0b84a4b7ec3e88263ff51dadf813260e4be4f9d5b8bab"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "c6dd2d83bba2c10927d484edd7290cca4deddd4e74a881209278f02d47fd8208"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cf86920e345cfd6fec606e40a2554a0fb67ddd04ed019df3ad6fff075c99955e"
metafile = true

[[files]]
file = "mods/vics-point-blank.pw.toml"
hash = "8da4ea127802f2b48b2741bb16e1c2212f850aef523b41f0b8b7036aa7858df7"
metafile = true
