name = "Silvereensmp"
author = "Silvereen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8933311290e631ff8e63b10540efe827e7419f7ff9385369104fc83209377103"

[versions]
forge = "45.4.3"
minecraft = "1.19.4"
